apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: vault
    finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
    destination:
        namespace: vault
        server: 'https://kubernetes.default.svc'
    source:
        repoURL: 'https://helm.releases.hashicorp.com'
        chart: vault
        targetRevision: "0.23.0"
    project: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
        - CreateNamespace=true
